### ISSUE TITLE
BUG: dewarping: auto: segfault N1

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/scantailor-experimental#10]
Hi @plzombie , @noobie-iv .

| screen | description |
| --- | --- |
| ![bug-dewarping-segfault-01](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/assets/12370082/1a4464bc-aea5-4c7f-a919-7f2a0da73d03) | Приветствую, Михаил и Роман. При автоматическом деварпинге (неудачном, но не "смертельном") внезпано возник SEGFAULT. Причём он возникает даже ежели не находишься на сбоящей странице, а просто переходишь с шага 3 на 4 на любой странице. Явно такую ситуацию можно "обойти". Начал дебаг, но сразу же получил указание на Eigen. Буду конечно потихоньку "ковырять замазку", но быстро дело не пойдёт. Страницу с проектом прилагаю (в проекте понадобится вручную подправлять пути к изображению). SEGFAULT происходит даже если переключиться с Curves на Perspective. |

[bug-dewarping-segfault-01.zip](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/files/13184259/bug-dewarping-segfault-01.zip) [600k]

**Comment by zvezdochiot** [comment]
Предварительный дебаг показал, что SEGFAULT происходит либо в:
https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/blob/1d9fe7f36b6ed66987661676620b4eefe221a31d/src/dewarping/DewarpingImageTransform.cpp#L470-L515
, либо в вызываемой ей функции.

**Comment by noobie-iv** [comment]
Win10x64 не вылетает, при любых видах деварпинга.

**Comment by zvezdochiot** [comment]
@noobie-iv , это с округлением возле нуля связано. В разных осях оно по разному отрабатывается. Ну и ладно. Порешил.
