### ISSUE TITLE
Margins, center_line + dark_theme?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/scantailor-experimental#12]
Hi @noobie-iv .

При использовании dark_theme в "Полях" ("Margins") начисто исчезают центральные метки:
![stex-margins-center_line](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/assets/12370082/643f97e2-c980-46cb-a824-f6d983bad5dd)
Думаю, это связано с изменением размерных единиц. Сам код центральных меток:
https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/blob/cfcd73196e4776a6d0ef22567e1151c479fa7ca4/src/filters/page_layout/ImageView.cpp#L315-L316
https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/blob/cfcd73196e4776a6d0ef22567e1151c479fa7ca4/src/filters/page_layout/ImageView.cpp#L320-L321
Не хотелось бы их "потерять". Очень они даже полезные.

PS: Метки исчезают не везде, а только там, где нет подложки (как в скрине). Ежели поля накладываются на "бумагу", то центральные метки как и положено "светятся" крестом.

**Comment by noobie-iv** [comment]
А я их вижу на обоих образцах. Просто на темном фоне они практически не заметны. Это та же проблема, из-за которой я заменил надписи со ссылками на кнопки перед добавлением темной темы. В STA вообще темы прошиты в том числе в код, и при переключении еще и дополнительные цвета меняют, кроме тех, что читаются из qss. В STU та же фигня с цветами выделения в окне миниатюр. По-хорошему, под такие цвета надо в язык QSS добавить свои типы объектов, чтобы и из можно было менять из тем. А по-простому, наверное, можно просто отрисовать такой маркер двумя контрастными линиями 3px+1px, вместо одной. Или заморочиться, и в backgroundColorForMatchSizeMode() сделать выбор цвета под фон, а не возврат одного фисированного как сейчас.

**Comment by zvezdochiot** [comment]
@noobie-iv say:
>А я их вижу на обоих образцах. Просто на темном фоне они практически не заметны.

Понятно. Ладно, в большинстве случаев видно. Только на некоторых не видно. Не стоит "суетиться".

**Comment by noobie-iv** [comment]
Я вообще только сейчас узнал, что они есть. Они же и на левом образце практически не видны. Я думал, что направляйки надо тырить из STA (а потом еще и править, потому что они глючат, если у картинок DPI разные). Собственно, не сложно поиграть в этой функции перьями и цветами, да подобрать более контрастный вариант. Но это опять день на эксперименты. Починить перевод стандартных кнопок - день гуглить и тестить. Починить размеры окна с темной темой - тоже. А моя главная идея будет простаивать.

На сегодня я в STD полностью вычистил деварп, и теперь можно пробовать пришить версию STEX. Все, что я делал до сегодняшнего дня, мозгов-то не требовало - темы, кнопки, копипаста из STU, удаления. А вот теперь, собственно, и начинается главная проверка: хватит мне соображалки, или надо уже забить на все эти игры с ST. И так несколько месяцев сюда добирался. Пришьется - будет первый релиз STD и планы на дальнейшее, нет - снесу профиль с гитхаба, и пойду сопли утирать.

**Comment by zvezdochiot** [comment]
@noobie-iv .

Так держать. :+1:
