### ISSUE TITLE
Error 0xc0000005 on program start under Win7х64

### ISSUE THREAD

**Issue by noobie-iv** [ImageProcessing-ElectronicPublications/scantailor-experimental#13]
Personal message from dwg.ru forum user **Vslav16m**. No additional information.

**Comment by plzombie** [comment]
Pls ask him which zip/installed did he use

**Comment by zvezdochiot** [comment]
@plzombie , думаешь файл попортился: https://remontka.pro/oshibka-0xc0000005-windows/ ?

**Comment by plzombie** [comment]
> @plzombie , думаешь файл попортился: https://remontka.pro/oshibka-0xc0000005-windows/ ?
> 

Нет. Я думаю, он версию с qt6 скачал или для arm64.

**Comment by noobie-iv** [comment]
**Vslav16m** response:

> Спасибо! На win 7 х 64 установиласть версия scantailor-experimental-0.2023.11.10-X86-64-install Работает!
