### ISSUE TITLE
Broken debug images

### ISSUE THREAD

**Issue by noobie-iv** [ImageProcessing-ElectronicPublications/scantailor-experimental#14]
Debug images are broken when moving from version 0.2023.10.11 to version 0.2023.10.24. Windows 10x64.

![0 2023 10 11](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/assets/146687817/854aad74-0201-4230-ac6e-6aed20eedb70)

![0 2023 10 24](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/assets/146687817/708184b3-9885-487b-84b8-cb3d5aaf40be)

**Comment by zvezdochiot** [comment]
https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/compare/0.2023.10.11...0.2023.10.24

**Comment by plzombie** [comment]
Ошибка в коммите https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/commit/ee95a6c981cc7df149b61f5186684d94f54af128
Я зачем-то обернул QWidget в QWidget. Сейчас перетестирую, закоммичу изменения.

**Comment by zvezdochiot** [comment]
Что за на?! А почему issue автоматически не закрылась? @plzombie не ставь больше между `fix` и номером ничего, пиши сполшняком `fix #14: тра-ля-ля...`
