### ISSUE TITLE
feature: 5. Margin: Alignment: Custom

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/scantailor-experimental#20]
Hi @plzombie , @noobie-iv .

Не получается добавить выравнивание "Custom" (на базе "Scaling", но ручное задание масштабного коэффициента через дополнительный, отключаемый в других выравниваниях `QDoubleSpinBox`). То тут, то там запарываюсь наглухо. Ежели сможете подсобить, то буду очень рад. С этим выравниванием система масштабирования STEX станет завершённой. Такие вот дела.

**Comment by noobie-iv** [comment]
Могу только поддержать морально. Гоп! Гоп!

У меня в планах зависнуть в отладчике, чтобы наконец понять, как там эта многопоточная лапша вообще работает. Ранее попытки понять это вычитыванием кода полностью провалились; веселые факты типа "знаете ли вы, что вызов updateSortOptions приводит к обновлению кеша картинок" просто выносят мозг. 

Без понимания я не встрою никакой новый функционал, потому что он всю программу цепляет. Если разберусь - смогу и в STEX чем-то помочь.

 А то, что я для STEX делал - это мелочи, на которые случайно натолкнулся в процессе поисков в STU.

**Comment by zvezdochiot** [comment]
Hi @plzombie , @noobie-iv .

Ещё раз обращаюсь к вам. Я опять в ступоре.

Для расчётов полей используется следующий базовый размер:
https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/blob/249d4e7c42bfe513bbccf6f8d6ef8ea814a3733b/src/stages/page_layout/PageLayout.cpp#L53-L55
https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/blob/249d4e7c42bfe513bbccf6f8d6ef8ea814a3733b/src/stages/page_layout/ImageView.cpp#L699-L701
Как мне "вывести на табло" и иметь возможность поменять ручками этот базовый размер? Мои попытки приводят к дичи: либо всё ломается, либо нишиша не работает.

**Comment by noobie-iv** [comment]
Я пока даже свою пародию до ума не довел, не говоря про вмешательство в полноценный СТ. Кеш превьюшек оказался сам многопоточным, внутре многопоточного тейлора. И они таки друг другу сигналят. Чтобы добавлять что-то в интерфейс, надо наизусть знать, в каких местах добавлять эти сигналы, и в каких местах ловить. Иначе что-то обязательно не законтачит. В больших программах, типа автокада, на такие темы здоровенные разделы справки с примерами приводят. А тут надо все такие места выискивать. На такие вопросы я смогу отвечать только после доделки своего микро-ст до минимально рабочего состояния.

**Comment by zvezdochiot** [comment]
Hi @plzombie , @noobie-iv , @trufanov-nok .

Кажется я "нащупал", почему так неудобно работать с полями в STEX.

Гораздо менее плохое управление полями можно получить разделив их на внешние (единные для всех страниц, строго роложительные) и индивидуальные (для каждой страницы свои, служат только для выравнивания, могут быть отрицательными, по ним и будет всё выравниваться, по умолчанию равны 0).

То есть, равность полей будет основана на том, что внешние аоля будут базироваться на:
https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/blob/65fcf099a6fa2214e5ce83744495f0c1862d294d/src/stages/page_layout/ImageView.h#L223
В то время как индивидуальные поля - это то, что реализовано сейчас, только дефолтное значение поменяется на 0. У обложек же индивидуальные поля будут равны внешним со знаком минус.

То есть всё практически остаётся таким же, как сейчас, только добавлается полоска внеших одинаковых полей, а нидивидуальные поля обеспечат выравнивание. Это гораздо удобнее и результат при этом хорошь.

PS: Сейчас мне для получения одинаковых полей приходится каждый раз патчить текущую версию STEX и прописывать какое то (обычно 3000) в качестве базового размера для полей в местах из предыдущего моего поста.

**Comment by zvezdochiot** [comment]
Модифицировал RelativeMargins под базовый размер: https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/commit/cb736af3b78b107282a4594a8238da7c84da13f2

Дальше модифицировать GUI: CheckBox+QDoubleSpinBox. При выключенном CheckBox базовый обнуляется и QDoubleSpinBox выключается, при включенном CheckBox QDoubleSpinBox включается и базовый приравнивается к getBaseRect.

Но! Как всё это сконектить, чтобы всё логично работало? Вот совсем не хочется колхоза.

**Comment by noobie-iv** [comment]
Могу разве что скинуть своего недоделыша. В нем базовую логику легче увидеть, чем в трех мегабайтах stex. Сейчас там единственный работающий фильтр - поворот, но две кнопки право/лево честно работают. А там уж по образцу все эти коннекты подключить можно будет.
 
Не работают превьюшки (коплю силы на борьбу с многопоточным кешем). Но, надеюсь, в кеш не надо логику от UI добавлять, и этого огрызка хватит. И под линухом оно не собирается, что-то в подключениях не находит, что-то в проекте cmake подкрутить надо. Но код и так можно посмотреть.

**Comment by zvezdochiot** [comment]
Спасибо @noobie-iv .

Сделай репу `scantailor-base` или `phototailor-base` и сбрасывай туда. Я уверен, что именно это позволит разрулить всю эту кашу и нормализвать код. Потому как к этапам можно заранее предьявить следующие требования:
1. они должны быть автоматизированы (как и сейчас)
2. они должны быть легко параметризированы (как этап "Вывод", не сложнее), т.е. вся автоматика должна легко управляться.
3. они дожны быть проще и легко сортироваться.

Отсюда этапы должны стать менее напряжными, но их дожно быть больше:
1. Ориентация
2. Разрезка
3. Фильтры
4. Искажения
5. Обрезка
6. Масштабирование (включая возможность исполдьзования biakima и RIS)
7. Макетирование (зоны с применением и Line и XSpline, а ежели постараться и Akima spline)
8. Чистка (удаление пятен с выделением зонами)
9. Вывод

Может быть что-то ещё (так что предусмотреть страивание этапов). Такие вот дела.

**Comment by noobie-iv** [comment]
На репу оно не тянет, это обрезок с целью понять как основной код устроен. А уж персортировка фильтров и макеты требуют сразу начать другую программу писать, это, по-моему, проще будет, чем вшивать это в готовый код. Но это ж на десять лет работы.

Так что я просто тут архив прикреплю, вдруг поможет:
[mvst.zip](https://github.com/user-attachments/files/16579528/mvst.zip)

**Comment by zvezdochiot** [comment]
@noobie-iv say:
>вдруг поможет

Чего то не попёрло:
```make
src/IntrusivePtr.h:51:43: error: invalid use of incomplete type ‘class Orientation::Settings’
   51 | inline void intrusive_unref(T &obj) { obj.unref(); }
      |                                       ~~~~^~~~~
```

**Comment by noobie-iv** [comment]
Я интересу ради пробовал собирать под линуксом, но у меня даже компиляция не прошла. Что-то надо в cmake править - Qt не находит автосгенерированные заголовки, и прекомпилированные заголовки тоже глючат. Если надо просто посмотреть вживую, что там есть - вот скомпилированный под винду, может, в эмуляторе заработает:
[install.zip](https://github.com/user-attachments/files/16580808/install.zip)
Qt-DLL я там занулил для уменьшения размера, их оригиналы можно из наших релизов забрать, от Qt5.

Если не заработает - придется время терять на разборки с cmake в линухах, прежде чем смогу что-то починить.

**Comment by noobie-iv** [comment]
Вот поправленная версия, собирается под Debian12, если вдруг в отладчике захочется погонять:
[mvst.zip](https://github.com/user-attachments/files/16595676/mvst.zip)

**Comment by zvezdochiot** [comment]
Спсб, @noobie-iv .

На этот раз скомпилилось. Будем посмотреть.

**Comment by zvezdochiot** [comment]
Разделить поля на внешнии и внутренние оказалось просто: текущии поля полностью стали внутренними + к ним присобачились внешние.: https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/commit/c270e0f9720f69ea5fdb4ba3f3a066c4aed09bc4

:question: Как присобачить к этому хозяйству GUI? Чтобы внешние поля были не константой (0.08), а регулировались?

**Comment by zvezdochiot** [comment]
"С горем пополам" разрулил ситуёвину: скопипастил с `Alignment`.

Теперь выравнивание стало ну очень удобно и страницы не обязаны иметь один размер. Такие вот дела. :+1:
