### ISSUE TITLE
geometric distortions 

### ISSUE THREAD

**Issue by konos93** [ImageProcessing-ElectronicPublications/scantailor-experimental#25]
it is possible on the distortion type have firstly page skew , after keystonning or curved lines not only one of those .

**Comment by zvezdochiot** [comment]
@konos93 . Do you mean sorting? Ask @noobie-iv , sorting is related to iterators, and I don’t understand anything about them. I won’t even be able to correct the code, since this code still needs to be entered at this stage.

**Comment by zvezdochiot** [comment]
Not actual. See https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/commit/6c21efef2688d68443728b8fa71ecccec130a639

**Comment by zvezdochiot** [comment]
Not actual. See https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/commit/6c21efef2688d68443728b8fa71ecccec130a639
