### ISSUE TITLE
dispute: simple dewarping

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/scantailor-experimental#37]
Hi, @noobie-iv .

Меня всё беспокоит, что, несмотря на конкретную путанность цилиндрической 2D модели исправления искажений,не всегда получается добиться достойного результата.

Оно то всё понятно, но беспокоит не сам этот факт, а то, что используя простейшую 1D линейную модель постолбчатого исправления искажений ([photoquick: example: dewarping](https://github.com/ImageProcessing-ElectronicPublications/photoquick-examples/tree/main/main/transform/geometry/dewarping)) удаётся получить результат немногим уступающий этой сложной и навороченной 2D модели.

Как так? И это при использовании всего лишь линейного (2 линии - 2 значения для каждого столбца) интерполянта?

Ведь никто же не мешает чуть "усложнить" эту модеь, внести в неё дополнительный параметр M - количество линий и использовать внутри каждого столбца уже не линейную, а (M-1)-степени интерполяцию. Не сильное ведь усложение, верно?

:question: Да это строго ручной способ исправления искажений, но не стоит ли вам поэкспериментировать с ним в ваших изысканиях?

**Comment by noobie-iv** [comment]
Слабо вот это развернуть?

![IMG_20240623_135052](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/assets/146687817/89942ed6-b865-4613-b46e-64732abbbdde)

В оригинале же программа под качественные исходники была. Поворот - от слегка криво лежащих в сканере листов. Перспектива - от фото ровного плоского листа чуть наискосок. А деварп - фото неприжатого разворота книги. Под другие виды деформаций нужны другие фильтры. Понятно, что после использования листа в качестве туалетной бумаги будут некоторые проблемы с обработкой.

Хотя у нас в строительстве именно такие документы норма. Мы до сих пор на согласования носим рулоны, свернутые в A4, для росписи гусиным пером. А потом с них надо снимать скан, и зашивать в PDF. А сканер у нас - A3, и у него старая несмазанная лампа, которая в неудачные дни вместо скана реальную гуглокапчу выдает. Вот мои сканы точно как эти фотки из примера выше и выглядят. Их потом приходится из огрызков в гимпе собирать. В особо тяжелых случаях их еще печатают повторно, носят на доподписи, и сканируют повторно обратно в PDF. Встречались даже патологии, когда очередной согласующий циркулем-измерителем мерил расстояния по координатной сетке, чтобы допуск 0.2мм не нарушен был. Вот где деварп нужен так нужен.

Мой дальний идеал ST - чтобы у него, как у PhotoQuick, была папка plugins, а в нее любой желающий мог относительно легко дописать что-то свое, например, внешний деварп прикрутить. Пока что в ST стадии прибиты гвоздями, и дергают друг друга через прямые ссылки. По-хорошему, это надо чистить, где-то одновременно с добавлением макетирования, потому что они оба основную логику ломают. Но это еще только через год обсуждать надо, я пока то ли в середине разборок с кодом, толи еще у начала. А уж править алгоритмы обработки, или писать свои я точно не буду, только вызов внешних, если получится это сделать.

**Comment by zvezdochiot** [comment]
@noobie-iv say:
>Слабо вот это развернуть?

Ну да, слабо:
![342020110-89942ed6-b865-4613-b46e-64732abbbdde dw1d](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/assets/12370082/eaa32626-81d6-48df-8ebc-18b3cb9d3aa9)
По двум линиям (линейная интерполяция) достаточно лажёво получается.

**Comment by noobie-iv** [comment]
Тут поверх цилиндра надо еще перспективу учитывать. И, возможно, линзовые искажения. А еще тут перелом наискосок слева вниз от последнего абзаца, где страницу пальцем придерживали, так что линейчатых поверхностей тут две - вдоль страницы и под 45°. Никакие простые деформации этого не починят. Тут нужна трассировка строк, чтобы все их выровнять по вертикали, и трассировка букв, чтобы выровнять по горизонтали. Причем трассировка строк в виде размытых изображений, как сейчас, не сработает, потому что будет глючить на заглавных буквах и на хвостиках Р,У,Д, и т.п.  Плюс в интерфейсе нужна возможность ткнуть пальцем в несколько линий, и сказать, что они должны быть ровными - на случай, когда автоматика не справится, или на картинках. Или исключить картинки из анализа. Подозреваю, что, даже если забить на все остальные идеи, и чинить только деварп, это тоже на несколько лет развлечение.

**Comment by zvezdochiot** [comment]
@noobie-iv say:
>Никакие простые деформации этого не починят.

Не факт. Я специально использовал самую примитивную модель (линейная интерполяция по двум линиям). Но даже на ней виден определённый "прогресс". По кубической интерполяции (четыре линии) ожидается значительно менее лажёвый результат. Не стал применять и перспективу, чтобы было видно её необходимость.

По трассировке строк: очень жаль, что так и не придуман алгоритм трассирующий низ строки, а не её середину. Это  бы многое упростило бы.

**Comment by noobie-iv** [comment]
Я имел ввиду "перспективу в направлении оси камеры". От нее буквы в центре шире букв с краю. Та перспектива, что в ST, распрямляет кривой четырехугольник в квадрат. А тут недостаточно выровнять строки по вертикали, их еще по горизонтали рихтовать надо. То есть еще вдоль направляющей нужны дополнительные параметры деформации, которые к краям буквы растягивают, а к середине сжимают. И, если это в автомате делать, программа должна подобрать положение камеры близко к странице, и форму искривления страницы хотя бы по двум направляющим, чтобы пересчитать результат в плоскость.

Плюс я специально прижал край пальцем, чтобы там буквы поползли - тут ни круглый цилиндр, ни линейчатый "ласточкин хвост" не сработают. Они оба этот угол криво восстановят. Это уже модель мятой бумаги со стыком разных поверхностей нужна. Или нужно распознавать буквы и выравнивать все побуквенно. 

![01](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/assets/146687817/43b94600-400a-4495-9d4a-922c64dd39d8)

И кстати, такие фото документов-срук тоже попадаются. Если прям припрет, и надо будет одну-две страницы починить, я это в Блендере сделаю. Нанесу текстуру на плоскость, порежу линиями на кривоугольники  "10букв X 10строк", распрямлю их вручную и отрендерю на плоскую камеру. Как такое, например, в GIMP сделать - хз. Но книгу так чинить слишком долго.

**Comment by zvezdochiot** [comment]
@noobie-iv say:
>Если прям припрет, и надо будет одну-две страницы починить, я это в Блендере сделаю.

Почему в Блендере, а не в QGIS? В QGIS есть локальное афинное преобрадование (по заданным точкам изображение делится на четырёхугольники, и к каждому четырёхугольнику применяется своё аффинное преобразование).

**Comment by noobie-iv** [comment]
Блендер интерактивный. В нем я вижу результат, прямо двигая точки. Не нужно полчаса тыкать исходные данные, а потом переделывать их из-за того, что результат не очень. В идеале так и в ST должно быть. А сейчас он как раз на QGIS похож - я вижу сетку деварпа на исходном изображении, а не окончательный результат, из-за этого туда-сюда ерзать надо. По исходным данным не понятно, будет результат правильный или нет. Для карт это еще норм, там же привязка к строго нанесенным точкам предполагается. А в книге откуда мне координаты букв знать?

**Comment by zvezdochiot** [comment]
@noobie-iv .

В ту же топку: изкажение линзы: [warp7p](https://github.com/ImageProcessing-ElectronicPublications/warp7p) (нужен [lodepng](https://github.com/lvandeve/lodepng)).

**Comment by noobie-iv** [comment]
@zvezdochiot 

Видел эти волшебные коэффициенты в программах для VR на телефон. Там их требовали вводить "по паспортным данным линз" для конкретной модели. Особенно радуют cx, cy. Если фото обрезали, прежде чем обрабатывать, как теперь центр найти? Видел формулы с ними (не помню где - возможно, на форумах скриптописателей для блендера) для оценки положения камеры (вроде как они даже достаточно известны тем, кто в теме), но там вроде как наблюдаемая геометрия должна быть известна, а у нас и ее подбирать надо.

Тут, скорее всего, что-то типа подбора наименьшими квадратами нужно, чтобы оттрассированные строки наилучшим способом распрямились. И это под наперед заданную модель изогнутого листа (например, два пространственных сплайна - верхний и нижний край листа - по трем...пяти точкам, плюс координаты камеры, а поверх эти линзовые формулы).

И есть сильное подозрение, что без трассировки вертикалей (например, по буквам), у этой задачи нет однозначного решения: может быть сильно изогнутый лист и сильно искривляющая линза, которые друг друга компенсируют. Искривление листа растягивает середину по вертикали, а линза сжимает. Если считать, что боковые края всегда ровные, то линзу можно по ним оценить - искажение центра по горизонтали должно быть только от линзы. Но тогда нужна трассировка краев страницы, или блока текста.

А если лист еще и мятый - так и оно, наверное, не поможет.

И, самое главное, я не буду участвовать в разработке или дописывании алгоритмов в ST, это слишком долго. Моя цель-миниум - добавить внешнюю обработку, и там пусть желающие используют что захотят. Я, правда, думал, что это будет сильно проще, а застрял на год. Сейчас в STD с эскизами вожусь - одно чиню, другое ломается. Когда с двадцатой попытки оно таки заработает - я, видимо, опять не пойму, почему 😄

**Comment by zvezdochiot** [comment]
@noobie-iv , да всё оно понятно. Просто мне понадобилось на определённом материале подавить линзу. Ну я ни капли не сумявшись использовал эту тулзу. Коэффициент искривления (первый) и масштаба (последний) подобрал глазомерно по характерному скану, центры же использовал дефолтные (0,5). Вопрос то был не выпрямить скан, а сделать боковые края прямыми. То, что автоматика здесь хрен получится - это стопудово, а вот как коррекция модели - очень даже ничего зашло. Более того: мало того, что сама математика простая, так её ещё можно упростить до компонентной: 
```
dX = a * (X - Xc) * kY
kY = (Y - Yc) * (Y - Yc) / height / height
```
где для выпрямление боков достаточно иметь один регулятор `a`.

Такие вот дела. :smile:
