### ISSUE TITLE
question about page final sizes 

### ISSUE THREAD

**Issue by konos93** [ImageProcessing-ElectronicPublications/scantailor-experimental#4]
scan tailor experimental gives around 220 kb each page lzw compression
scan tailor advanced around 80 kb ccitt t.6 compression

because i use djvusmall and after that abbyfinereader12 i can see differences on the final pdf size. 
i use a 2 camera diy bookscanner so the cropped content o STA is not the same but i prefer that due to the final size and i play with the margins on koreader on my ebook
here some results https://wetransfer.com/downloads/d941d50f9131ef22d71a90c0bc8b680920230920012354/97dce6

how difficult is to make a compression for scantailor experimental to have page sizes like scantailor advanced?

**Comment by zvezdochiot** [comment]
@konos93 say:
>how difficult is to make a compression for scantailor experimental to have page sizes like scantailor advanced?

I don't know this. And there is no one to do this, because I am an amateur, not a pro. And I don’t understand such things.
