### ISSUE TITLE
Possible bug: TIFF LZW compression incorrect for files output from ST?

### ISSUE THREAD

**Issue by gasparschott** [ImageProcessing-ElectronicPublications/scantailor-experimental#43]
The original tif files that I process with ST are saved with LZW compression. While the output files from ST seem to be compressed as well, when they are opened in Photoshop, edited, and saved, Photoshop always opens a "Save As" window (which is annoying in itself) and the "LZW" option is always unchecked, as if the file was *not* compressed; indeed, 

Interestingly, the TIFF Properties Metadata for ST-processed files shows the Compression value as "4", whereas in the same file saved from Photoshop with LZW (and in the original, pre-ST-processed file) it is "5". In uncompressed TIFFs this value is "1".

Could this be a bug in ST, or could some setting be added to ST to allow the user to choose the compression method for exported files?

Thanks.

**Comment by gasparschott** [comment]
Sorry, I should have mentioned that I'm on macos, so I can't use the .rar.
What other issue also mentions this?

**Comment by plzombie** [comment]
Hi @gasparschott 
In ST black and white pages compressed with CCITTFax4 (Compression = "4") and colored pages compressed with LZW (Compression = "5")
For bw pages it's set somewhere here https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/blob/main/src/TiffWriter.cpp#L259

**Comment by zvezdochiot** [comment]
Hi @gasparschott .

ST is always (ALWAYS!) used in conjunction with batch image processors. Use [GraphicsMagick](http://www.graphicsmagick.org/) with STEX.

**Comment by gasparschott** [comment]
Thanks, I don't know why I didn't think of that—I use GM for all sorts of other things. A blind spot, I guess.
