### ISSUE TITLE
setMetricsOptions VS crash

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/scantailor-experimental#46]
Hi @plzombie , @noobie-iv .

Ситуёвина следующая: после добавления:
https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/blob/611b4c4384872a61586cc31ec9aa181c82de4cab/src/stages/output/Task.cpp#L343-L348
для обновления метрик по завершению `process` в `OutputGenerator` иногда наблюдаются падения.

Как это происходит?

На первой странице назначаю все значения фильтров, порогов и т.д. Применяю их ко всем страницам. Запускаю поточную обработку. Обработка проходит по всем страницам и возвращает на первую. Прикасаюсь к GUI мышью -> падение (не всегда, скорее иногда).

Что за нах?

На oomkiller не похоже (ИМХО). В момент прикосновения память не пользуется. Больше похоже на то, что какой то объект не инициализирован и при обращении к нему -> бац, "приходите в следующий раз".
  
PS: В самом OutputGenerator metrics - это публичный структура (объект), без использования функций присвоения. Почему? Ну не хотелось мне возиться с функциями присвоения и переносить metrics в private. Сделал public для прямого доступа.

Коммиты - участники:
* https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/commit/d97f9ae430ad546065a38236a113109511cd333e

**Comment by noobie-iv** [comment]
Под виндами уронить не удается ни релиз, ни дебаг. Зато под виндами не работает выбор дополнительного фильтра из списка - на него нет абсолютно никакой реакции. Список неактивен с самого первого релиза - 0.2024.05.18 (filters).

**Comment by zvezdochiot** [comment]
@noobie-iv say:
>не работает выбор дополнительного фильтра

Всё правильно. Выбор ничего не меняет, ибо это всего лишь ГУИ списка. Ты не просто выбери, а коефициент измени.

PS: Может реально oomkiller? Но почему падение только после прикосновения? Иллюзия?

**Comment by noobie-iv** [comment]
На виртуалке тоже не ловится:
g++ (Debian 12.2.0-14) 12.2.0

**Comment by zvezdochiot** [comment]
@noobie-iv , понял тебя. Значит ложная "паника"? Буду разбираться. Закрою позже.

**Comment by noobie-iv** [comment]
Может, конкретная версия линукса/компилятора или конкретный проект?

**Comment by zvezdochiot** [comment]
```shell
$ g++ --version
g++ (Debian 12.2.0-14) 12.2.0
```
Скорее всё-таки oom-killer.

**Comment by zvezdochiot** [comment]
После многократного тестирования склоняюсь к тому, что это oom-killer срабатывал.
